# Generated by Django 4.1 on 2022-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartdiseasepred", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datas",
            name="thal",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
