# Generated by Django 4.1 on 2022-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartdiseasepred", "0004_alter_doctor_consultinghour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="Hotline",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="Phone",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
