# Generated by Django 4.1 on 2022-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartdiseasepred", "0005_alter_doctor_hotline_alter_doctor_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datas",
            name="sex",
            field=models.PositiveIntegerField(
                choices=[("1", "Female"), ("0", "Male")], null=True
            ),
        ),
    ]
